name: Deploy to Amazon Cloudfront

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      setRegion:
        description: 'Set region to deploy:'     
        required: true
        default: 'us-east-1' 
        type: choice
        options:
        - us-east-1
        - us-east-2
      setEnvironment:
        description: 'Set environment to deploy:'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - prd
        - dev
        - stg  
      appName:
        description: 'Application name:'
        required: true
env:
  AWS_REGION: ${{ github.event.inputs.setRegion }}                                                      # set this to your preferred AWS region, e.g. us-west-1
  ENV: ${{ github.event.inputs.setEnvironment }} 
  APP_NAME: ${{ github.event.inputs.appName }}
  HEALTHCHECK_DEV: "template-s3-cloudfront.dev.cloud.dex.co"
  HEALTHCHECK_STG: ""
  HEALTHCHECK_PRD: ""

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.setEnvironment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build
      run: |
        ./scripts/build-app.sh

    - name: Deploy Application
      run: |
        aws s3 sync --no-follow-symlinks app/ s3://$APP_NAME-$ENV-bucket/

    - name: Check Environment
      run: |
        ./scripts/healthcheck.sh $ENV
